README.md, manifests/tor-client-updater/tor-client-updater-darwin-manifest.json, manifests/tor-client-updater/tor-client-updater-linux-manifest.json, manifests/tor-client-updater/tor-client-updater-win32-manifest.json, package.json, scripts/packageTorClient.js, scripts/uploadTorClient.js
=> Add support for packaging and uploading Tor client updater

lib/util.js, scripts/uploadComponent.js, scripts/uploadThemes.js, scripts/uploadTorClient.js
I actually meant to include this commit in the last PR here:
https://github.com/brave/brave-core-crx-packager/pull/13
=> Add arg for vault updater path for updating extensions json data

lib/util.js, manifests/ipfs-daemon-updater/ipfs-daemon-updater-darwin-manifest.json, manifests/ipfs-daemon-updater/ipfs-daemon-updater-linux-manifest.json, manifests/ipfs-daemon-updater/ipfs-daemon-updater-win32-manifest.json, package.json, scripts/packageIpfsDaemon.js, scripts/uploadIpfsDaemon.js
Package IPFS files into platform-specific CRX files.
=> Package IPFS

lib/util.js
Fix https://github.com/brave/brave-core-crx-packager/issues/26
=> Remove quoting binary for generateCRXFile so command runs on macOS

lib/util.js
=> Use correct S3 options and brave-core-specific bucket

README.md, scripts/packageTorClient.js
=> Use latest Tor client

scripts/packageTorClient.js
fixes https://github.com/brave/brave-core-crx-packager/issues/35
=> Issue 35: Tor client v0.3.4.9

package-lock.json, package.json
Fix https://github.com/brave/brave-core-crx-packager/issues/37
I also did a fresh update of package-lock.json
=> Update deps to work with node 11

README.md
Fixes https://github.com/brave/brave-core-crx-packager/issues/39
=> update README to use npm instead of yarn

scripts/packageTorClient.js
auditors: @emerick, @riastradh-brave
=> Issue 42: Updating tor binaries to 0.3.5.7

scripts/packageComponent.js
fixes https://github.com/brave/brave-core-crx-packager/issues/45
=> fix path argument type bug

scripts/packageTorClient.js
=> Signed tor_0.3.5.7

scripts/packageComponent.js
=> Issue 53: Adding StorageTrackingProtection.dat to local-data-files component

package-lock.json
=> Update node-gyp dep to eliminate tar security vulnerability

package-lock.json, package.json, scripts/packageComponent.js
Fixes https://github.com/brave/brave-core-crx-packager/issues/57
=> Update deps and fix whitespace for linter

scripts/packageTorClient.js
fix https://github.com/brave/brave-core-crx-packager/issues/60
=> Issue 60: Update tor client to v0.3.5.8

scripts/generateAdBlockRustDataFiles.js
@bbondy looks like between the two of us force-pushing to #74, this change ended up getting reverted.
=> Remove unused uBlock git archive URL

package-lock.json, package.json
Updates adblock-rs so that the notification filters list is included in the DAT
=> update adblock-rs -> 0.1.38 to include notification filters

scripts/generateNTPSponsoredImages.js
The client needs a schema version to detect any future changes in this file format and decide not to parse, avoiding errors. Likewise, this script needs to detect if the file format has changed.
=> NTP Sponsored Images format emits and responds to schema version

scripts/generateNTPSponsoredImages.js
Right now the CI server is attempting to download `244 * 4 = 976` images all at the same time, causing the request library to fail.
This changes it to download regions in order.
=> NTP Sponsored Images regions are downloaded one by one instead of requesting every resource from every region at the same time.

README.md
Added Development section to wiki to explain how to generate public/private keypair and component ID.
=> Added Development section to Wiki

scripts/packageTorClient.js
=> Fix 94: Update shasum for signed windows tor-client

package-lock.json, package.json
=> Fix 99: Update npm packages to fix audit issues

scripts/packageTorClient.js
=> Fix 103: Update hashes for tor v0.3.5.10

package.json, scripts/packageComponent.js
Introduces SpeedReader component updater to allow for updating rewriting whitelists
=> SpeedReader component updater

package.json, scripts/uploadComponent.js
keeps packaging pipelines to be similar to other components
=> alias commands for speedreader packaging/uploading

scripts/generateAdBlockRustDataFiles.js
Otherwise the rest of the promise chain doesn't run
=> Make sure promise from generateResourcesFile gets resolved

lib/adBlockRustUtils.js, package-lock.json, package.json, scripts/generateAdBlockRustDataFiles.js, test/generateResourcesFile.js
@bbondy follow-up to #109.
I suppose there should also be some CI work to ensure that tests are exercised regularly?
=> Add testing framework + test behavior of generateResourcesFile

package-lock.json, package.json
https://github.com/brave/ethereum-remote-client/releases/tag/0.1.54
=> Upgrading ethereum-remote-client to v0.1.54

lib/util.js, scripts/uploadComponent.js, scripts/uploadIpfsDaemon.js
Fix https://github.com/brave/brave-core-crx-packager/issues/135
=> Update DB when uploading IPFS component too

scripts/uploadRawAdblock.js
Fix https://github.com/brave/brave-core-crx-packager/issues/110
=> Skip over CRX files when enumerating raw files for upload

package.json, scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Fix #139 
This is to support creating a CI job for publishing ipfs component extension, please see https://github.com/brave/devops/issues/3267 for more context.
=> Separate download-ipfs-daemon from package-ipfs-daemon

scripts/downloadIpfsDaemon.js
=> Update ipfs to v0.6.0

lib/util.js
Fix https://github.com/brave/brave-core-crx-packager/issues/146
=> Use putObjectTagging for tagging of latest release too.

scripts/packageIpfsDaemon.js
Fix the bug that download script is loaded during upload step which will overwrite our signed binaries in CI jobs.
=> Fix ipfs upload

scripts/generateClientModelParameterFiles.js, scripts/packageClientModelParameterComponent.js
we decided to have a component for each country _and_ each language so generated new keys/ids for components respectively.
=> split locale out into iso country and language components

scripts/packageTorClient.js
=> Fix 154: Update tor client to v0.3.5.11

scripts/packageComponent.js
Want a more dynamic way of tweaking distilled content styling than possible through the browser update cycle
=> includes SpeedReader content stylesheet in component packaged files

lib/ntpUtil.js, package.json, scripts/generateYoutubedown.js, scripts/packageNTPSuperReferrerComponent.js, scripts/packageNTPSuperReferrerMappingTableComponent.js, scripts/packageYoutubedown.js, scripts/uploadComponent.js
npm run generate-youtubedown -- --key "private key file path"
npm run package-youtubedown -- --binary "chrome bin path" --key "private key file path" 
npm run upload-youtubedown-component -- --crx-directory ./build/youtubedown/output
=> Youtubedown.js packager

lib/ntpUtil.js, scripts/generateNTPSponsoredImages.js, scripts/generateNTPSuperReferrer.js
Issue: https://github.com/brave/brave-browser/issues/10206
=> Support NTP SI/SR V2

scripts/importCWSComponents.js, scripts/packageClientModelParameterComponent.js, scripts/packageComponent.js, scripts/packageIpfsDaemon.js, scripts/packageNTPSponsoredImagesComponents.js, scripts/packageNTPSuperReferrerComponent.js, scripts/packageNTPSuperReferrerMappingTableComponent.js, scripts/packageTorClient.js, scripts/packageYoutubedown.js, scripts/uploadComponent.js
relates to https://github.com/brave/devops/issues/2479 https://github.com/brave/devops/issues/2483
=> update dynamo region for migration

scripts/packageTorClient.js
=> Fix #184: Update tor to 0.4.4.6

package-lock.json, package.json
This contains the fix for https://github.com/brave/adblock-rust/issues/150
=> Update adblock-rust dependency to 0.3.4

manifests/ipfs-daemon-updater/ipfs-daemon-updater-darwin-manifest.json, manifests/ipfs-daemon-updater/ipfs-daemon-updater-linux-manifest.json, manifests/ipfs-daemon-updater/ipfs-daemon-updater-win32-manifest.json
Fix https://github.com/brave/brave-core-crx-packager/issues/193
=> update IPFS manifest info

README.md, lib/util.js
For https://github.com/brave/devops/issues/4103
=> Lock down public access for extension buckets

package-lock.json, package.json
Bump for latest 1.0.25 candidate
=> Bumping ethereum-remote-client to v0.1.85

scripts/uploadRawAdblock.js
Relates to https://github.com/brave/devops/pull/4332
=> Remove public ACL from ablock-data

scripts/packageTorClient.js
=> Fix #202: Update tor-client to 0.4.5.6

scripts/packageTorClient.js
Requires for https://github.com/brave/devops/issues/4432
=> Update demo tor binaries

scripts/packageTorClient.js
Fix https://github.com/brave/brave-core-crx-packager/issues/209
=> Fix #209: Update tor-client to 0.4.5.7

scripts/packageTorClient.js
Fix https://github.com/brave/brave-core-crx-packager/issues/213
=> Fix #213: Update tor 0.4.5.7 to OpenSSL 1.1.1k

scripts/packageTorClient.js
=> Fix #222: Update to tor v0.4.5.8

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/15937
Note: Please don't merge it yet as I'm still testing the update on staging first.
=> Update go-ipfs to v0.9.0

scripts/packageTorClient.js
Fix https://github.com/brave/brave-core-crx-packager/issues/228
=> Fix #228 - Update to tor-0.4.5.9

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Updating ipfs node to released 0.9.0
https://github.com/brave/brave-browser/issues/16578
=> Update ipfs to  0.9.0

CHANGELOG-go-ipfs.md
@bbondy @spylogsster @kjozwiak r?
=> Add go-ipfs-0.9.0 release note to new CHANGELOG-go-ipfs.md file

CHANGELOG-go-ipfs.md
@bbondy @kjozwiak @spylogsster r?
=> Bump actual ship date to July 1, 2021

manifests/wallet-data-files-updater/manifest.json, package.json, scripts/packageComponent.js
Fix https://github.com/brave/brave-core-crx-packager/issues/238
=> Add Wallet Data Files Updater component

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/17172
- Updated the ipfs node to v0.9.1
=> Update ipfs node to v0.9.1

scripts/downloadIpfsDaemon.js
Changed urls for ifps libraries
=> Changed urls for ipfs libraries

CHANGELOG-go-ipfs.md
@spylogsster @bbondy @kjozwiak r?
=> Add go-ipfs 0.9.1 release note

scripts/packageTorClient.js
=> Fix #226 - Update to tor-0.4.5.10

scripts/packageTorClient.js
=> Fix ##253 - Update to Openssl 1.1.1l for tor client

.gitignore, package-lock.json, package.json, scripts/generateAdBlockRustDataFiles.js
Add support for parsing redirect-url
=> Upgrade adblock-rs to 0.4.0

scripts/generateAdBlockRustDataFiles.js
`parse_redirect_urls` => `include_redirect_urls`
=> Fix variable name for redirect URLs parse option

scripts/packageTorClient.js
fix https://github.com/brave/brave-core-crx-packager/issues/279
=> Fix #279 - Update to tor-0.4.5.11

lib/util.js, package-lock.json, package.json
Resolves https://github.com/brave/brave-core-crx-packager/issues/276
=> Resize svg images before converting them to png for wallet

package-lock.json, package.json, resources/tor/torrc, scripts/packageTorClient.js
This is needed by https://github.com/brave/brave-core/pull/11406
=> Add torrc bundled with tor binary

lib/util.js, package-lock.json, package.json
Resolves https://github.com/brave/brave-browser/issues/20196
- Fixing audit issue by updating library to latest version
=> Update aws-sdk to latest version

lib/ntpUtil.js, lib/util.js, package-lock.json, package.json, scripts/ntp-sponsored-images/generate.js, scripts/ntp-sponsored-images/package.js, scripts/ntp-sponsored-images/params.js, scripts/ntp-sponsored-images/params.test.js, tsconfig.json
This repo could do with some type validation.
I only did ntp-sponsored-images files and files they include (utils.js etc) so far.
=> Type checking

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/20072
Add update to v0.11.0
=> Update ipfs library to v0.11.0

scripts/downloadIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/20443
=> Use github to download go-ipfs node

CHANGELOG-go-ipfs.md
@spylogsster @kjozwiak @srirambv r?
=> Add go-ipfs-0-11-0 release note

.github/workflows/submodule-update.yml
As part of https://github.com/brave/devops/issues/6517, this change will increase the frequency of the synchronisation to hourly, and include an ability to trigger the sync manually if required.
=> uBlock Fork Sync Improvements

package-lock.json
Needed for https://github.com/brave/brave-browser/issues/20826.
=> Update extension whitelist

package-lock.json
Fixes brave/extension-whitelist#48
=> Update extension-whitelist to ship brave/extension-whitelist#48

scripts/packageTorClient.js
fix https://github.com/brave/brave-core-crx-packager/issues/313
=> update to tor 0.4.6.9 and libevent 2.1.12-stable

package-lock.json
Fixes brave/extension-whitelist#50
=> Update extension-whitelist to unblock LOC extension

scripts/ntp-sponsored-images/package.js, scripts/packageBraveAdsResourcesComponent.js, scripts/packageComponent.js, scripts/packageIpfsDaemon.js, scripts/packageNTPBackgroundImagesComponent.js, scripts/packageNTPSuperReferrerComponent.js, scripts/packageNTPSuperReferrerMappingTableComponent.js, scripts/packageTorClient.js, scripts/packageYoutubedown.js
Relates https://github.com/brave/brave-browser/issues/873
Main PR: https://github.com/brave/brave-core-crx-packager/pull/337#issuecomment-1043551835
=> Add publisher-proof-key for backward compatibility

package-lock.json, package.json
Revert commit a9e05269582d2863411ffb4dc1c5b2c6a3a30649
=> Revert Update dependency aws-sdk to v2.1082.0

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/21219
updated to v0.12.0
=> Update IPFS node to go-ipfs v0.12.0

scripts/generateAdBlockRustDataFiles.js
Also uses this to compile iOS cosmetic filter rules
Fixes https://github.com/brave/brave-core-crx-packager/issues/342
=> Expose `rule_types` value from `generateDataFilesForList`

package-lock.json
To make it compatible with newer Node.js versions.
=> migrate package-lock.json to v2

.github/workflows/node.js.yml, Dockerfile, package-lock.json, package.json, scripts/packageComponent.js
This data is no longer used by brave-core
Also provide docker image containing everything needed for npm install. Can be run via:
```
docker run --rm --interactive --tty --volume $PWD:/app --workdir /app $(docker build -q .) npm install
```
=> Remove autoplay whitelist

.github/workflows/node.js.yml
Resolves https://github.com/brave/devops/issues/7024
=> Add more steps to CI

README.md, package-lock.json, package.json
Fix https://github.com/brave/brave-core-crx-packager/issues/378
This changes the lockfile format because I needed to downgrade to Node
14 in order to install hashset-cpp.
=> Fix npm audit minimist error

scripts/packageTorClient.js
=> Update tor to 0.4.6.10

package-lock.json, package.json, scripts/packageComponent.js
=> Remove ReferrerWhitelist.json from builds

.github/workflows/node.js.yml, lib/adBlockRustUtils.js, lib/util.js, package.json, scripts/downloadIpfsDaemon.js, scripts/generateAdBlockRustDataFiles.js, scripts/generateBraveAdsResourcesComponentInputFiles.js, scripts/generateManifestForRustAdblock.js, scripts/generateNTPBackgroundImages.js, scripts/generateYoutubedown.js, scripts/importCWSComponents.js, scripts/ntp-sponsored-images/generate.js, scripts/ntp-sponsored-images/package.js, scripts/ntp-sponsored-images/params.test.js, scripts/packageBraveAdsResourcesComponent.js, scripts/packageComponent.js, scripts/packageIpfsDaemon.js, scripts/packageNTPBackgroundImagesComponent.js, scripts/packageNTPSuperReferrerComponent.js, scripts/packageNTPSuperReferrerMappingTableComponent.js, scripts/packageTorClient.js, scripts/packageYoutubedown.js, scripts/uploadComponent.js, scripts/uploadRawAdblock.js, test/generateResourcesFile.js
Resolves #267 
I highly recommend looking at each commit separately. One of those (the largest one) is the output of running a tool to fix a lot of straightforward lint errors. The other ones are manual edits and should be looked at more carefully.
=> Fix lint errors and run it as part of CI

scripts/generateBraveAdsResourcesComponentInputFiles.js, scripts/packageBraveAdsResourcesComponent.js
Reverts brave/brave-core-crx-packager#421
=> Revert "add addition country support"

scripts/generateBraveAdsResourcesComponentInputFiles.js, scripts/packageBraveAdsResourcesComponent.js
Reverts brave/brave-core-crx-packager#429
=> Revert "Revert "add addition country support""

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/23427
=> Update IPFS version to 0.13.0

CHANGELOG-go-ipfs.md
@cypt4 @spylogsster @srirambv r?
=> Add IPFS 0.13.0 release notes

package-lock.json, package.json
Reverts brave/brave-core-crx-packager#438
=> Revert "Update dependency aws-sdk to v2.1181.0"

scripts/packageTorClient.js
See brave/tor_build_scripts#103.
=> Rebuilt Tor 0.4.7.8 (new Windows signing key)

package-lock.json
Fixes https://github.com/brave/brave-core-crx-packager/issues/452
=> Update brave-site-specific-scripts version

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/24179
=> Update go-ipfs to 0.14.0

CHANGELOG-go-ipfs.md
@cypt4 @spylogsster r?
(Please don't merge until we've verified our push to production.)
=> Add IPFS 0.14.0 release notes

scripts/packageTorClient.js
See https://github.com/brave/tor_build_scripts/pull/108
=> Update Tor to 0.4.7.10

package-lock.json, scripts/packageComponent.js
Added clean-urls shipment as part of https://github.com/brave/brave-browser/issues/23315
=> Added clean-urls

CHANGELOG-go-ipfs.md
@cypt4 @srirambv r?
Will hold off merging until we've pushed to prod 👍
=> Add kubo 0.15.0 release notes

scripts/generateBraveAdsResourcesComponentInputFiles.js, scripts/packageBraveAdsResourcesComponent.js
'AR', 'BR', 'ID', 'MX', 'MY', 'PH', 'RU', 'TH', 'TR', 'VN'
=> Additional countries

package-lock.json
Resolves https://github.com/brave/brave-core-crx-packager/security/dependabot/5
=> fix minimatch vulnerability

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/25889
=> Update kubo to 0.16.0

scripts/packageTorClient.js
See https://github.com/brave/tor_build_scripts/pull/111 for the changes.
=> Update Tor to 0.4.7.10-2

scripts/generateAdBlockRustDataFiles.js
See https://github.com/brave/adblock-resources/pull/92 for reference
=> remove Brave scriptlets from non-Brave lists

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/26996
=> Update Kubo to 0.17.0

package-lock.json
Included changes are:
https://github.com/brave/playlist-component/compare/da641e552377629b72fe4224d6c665d2441d45ed...5434730bf7342f1ba5c057f1640882bb38604a85
=> Bump up playlist-component to latest version

package-lock.json, package.json
This fixes the outstanding npm audit issues.
=> Update out-of-date dependencies

package.json, scripts/packageComponent.js
=> Package https-upgrade-exceptions-list.txt from adblock-lists

scripts/packageTorClient.js
https://github.com/brave/tor_build_scripts/pull/115
=> Upgrade tor to 0.4.7.13-0

CHANGELOG-go-ipfs.md
fixes https://github.com/brave/qa-resources/issues/502
fixes https://github.com/brave/brave-browser/issues/27965
=> Add Release Notes for Kubo 0.18.1

package.json, scripts/uploadComponent.js
Followup to #593, intended to be merged once Jenkins jobs are switched over to the new script in https://github.com/brave/devops/pull/9403
=> Remove specialized upload scripts

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/29556
Testing passed :https://github.com/brave/brave-browser/milestone/386
=> Update Kubo to 0.19.1

CHANGELOG-go-ipfs.md
Fixes https://github.com/brave/qa-resources/issues/520
=> Add Release Notes for Kubo 0.19.1

scripts/generateNTPBackgroundImages.js
And cleanup error handling in general for this script
Some runs of this branch:
Showing errors - https://ci.brave.com/view/all-extensions/job/brave-core-ext-ntp-background-images-component-dev/21
Showing success - https://ci.brave.com/view/all-extensions/job/brave-core-ext-ntp-background-images-component-dev/22
=> Handle bad http status for ntp bg image

scripts/ntp-sponsored-images/region-platform-component-metadata.js
Add a new set of components that covers each NTP SI region for iOS
=> iOS component metadata for NTP SI

scripts/generateAdBlockRustDataFiles.js
Required for https://github.com/brave/adblock-resources/pull/112
=> Prepare exception-exception list components

scripts/generateManifestForRustAdblock.js
=> Generate manifest file for exception-exceptions list

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/30652
=> Update kubo to 0.20.0

CHANGELOG-go-ipfs.md
Closes https://github.com/brave/qa-resources/issues/530
=> Release notes for Kubo 0.21.0

scripts/generateAdBlockRustDataFiles.js
See https://github.com/brave/slim-list-lambda/pull/86 for more context
=> Use raw adblock dat format

manifests/ipfs-daemon-updater/ipfs-daemon-updater-win32-arm64-manifest.json, scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-core-crx-packager/issues/503
=> ipfs on windows arm64

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/32149
=> Update Kubo to 0.22.0

CHANGELOG-go-ipfs.md
Closes https://github.com/brave/qa-resources/issues/534
=> Add releases notes for IPFS/Kubo 0.22.0

scripts/packageTorClient.js
See https://github.com/brave/tor_build_scripts/pull/119 and https://github.com/brave/tor_build_scripts/pull/121 for the full changelog.
=> Tor 0.4.8.6

lib/adBlockRustUtils.js
Should fix https://github.com/brave/brave-browser/issues/33535 for now in the aftermath of https://github.com/brave/brave-core/pull/20442
=> Remove permissions for now

lib/adBlockRustUtils.js, lib/sentry.js, package-lock.json, package.json, scripts/generateAdBlockRustDataFiles.js
Should prevent issues with particular list sources <sub><i>I'm looking at you, <code>https://adblock.ee</code></i></sub> from blocking other component releases.
=> Capture download failures in Sentry without aborting

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolve https://github.com/brave/brave-browser/issues/33447
=> Updated Kubo to v0.23.0

lib/adBlockRustUtils.js
As per https://github.com/brave/uBlock/pull/183/commits/9d3acd91b8b60a8de4af55e6131af79ca03cb8d5#diff-91b364713e60c5b5cbb694ed5deabcefba6c2375e759336bc9c45ba46154ad99R237-R238
=> allow dependencies to be JS resources

CHANGELOG-go-ipfs.md
Closes https://github.com/brave/qa-resources/issues/544
=> Add release notes for 0.23.0

README.md, lib/util.js, package.json, scripts/generatePuffpatches.js
Revert the revert (#726), fix the race condition
Relates to #704
=> Implement differential patches

scripts/packageNTPSuperReferrerComponent.js
=> remove another undefined argument from stageDir

scripts/packageTorClient.js
See https://github.com/brave/tor_build_scripts/pull/126 and https://github.com/brave/tor_build_scripts/pull/127 for the list of changes.
=> Tor 0.4.8.9

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolve https://github.com/brave/brave-browser/issues/34188
=> Updated Kubo to v0.24.0

CHANGELOG-go-ipfs.md
Fixes: https://github.com/brave/qa-resources/issues/545
=> Add Release Notes for kubo 0.24.0

scripts/generateAdBlockRustDataFiles.js
no longer needed as of https://github.com/brave/devops/pull/11171
=> remove iOS-specific adblock logic

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolve https://github.com/brave/brave-browser/issues/34896
=> Updated Kubo to v0.26.0

lib/util.js, package-lock.json, package.json, test/testAdBlock.js
=> Remove `ajv` and `tmp` dependencies

lib/util.js
followup to #867 (thanks @wknapik)
=> workaround rename across filesystem error

README.md, scripts/packageNTPBackgroundImagesComponent.js, scripts/packageNTPSuperReferrerComponent.js, scripts/packageNTPSuperReferrerMappingTableComponent.js, scripts/packagePlaylist.js
Closes https://github.com/brave/brave-core-crx-packager/issues/863
=> use `--key-file` everywhere

scripts/packageTorClient.js
https://github.com/brave/tor_build_scripts/pull/145
=> Tor 0.4.8.10-1 update

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolve https://github.com/brave/brave-browser/issues/36531
=> Update Kubo to 0.27

CHANGELOG-go-ipfs.md
Closes https://github.com/brave/qa-resources/issues/586
=> Add Release Notes for Kubo 0.27.0

package-lock.json
Fixes failing CI (ref https://github.com/neon-bindings/neon/issues/1049)
=> Update cargo-cp-artifact to v0.1.9

scripts/downloadIpfsDaemon.js, scripts/packageIpfsDaemon.js
Resolve https://github.com/brave/brave-browser/issues/38979
=> Update Kubo to 0.29.0

CHANGELOG-go-ipfs.md
Fixes https://github.com/brave/qa-resources/issues/591
=> Add Release Notes for Kubo 0.29.0

scripts/packageTorClient.js
Once https://github.com/brave/tor_build_scripts/pull/147 has been merged.
=> Codesign Windows Tor client with new certificate

lib/adBlockRustUtils.js, scripts/generateAdBlockRustDataFiles.js, test/testAdBlock.js
This allows us to exclude firefox rules.
Closes #923
=> Preprocessor adblock rules and apply if-statements

lib/util.js
Resolves https://bravesoftware.slack.com/archives/CG08GKTFS/p1734497059322079
=> Increase upload to s3 timeout

scripts/packageTorClient.js
See https://github.com/brave/tor_build_scripts/pull/149/commits for the list of changes.
=> Upgrade tor to 0.4.8.13 and OpenSSL to 3.4.0

scripts/packageTorClient.js
https://github.com/brave/tor_build_scripts/pull/153
=> Tor 0.4.8.14-0 update

component-data/youtube-script-injector/scripts/extra-controls-pip.js
This PR resolves 
https://github.com/brave/brave-browser/issues/44933 once https://github.com/brave/brave-core/pull/26355 will be merged.
=> Add support for PIP in youtube website

lib/util.js
=> feat: Add extension size to DynamoDB items
