- README.md
- lib/util.js
- package-lock.json
- package.json
- scripts/packageComponent.js
- scripts/packageThemes.js
- scripts/packageTorClient.js
- scripts/uploadComponent.js
- scripts/uploadThemes.js
- scripts/uploadTorClient.js
Fixes #8 
Refactors scripts to upload CRX files without requiring user to specify the version number on the command line.
> Parse manifest.json automatically when uploading CRX file

- lib/util.js
- package-lock.json
- package.json
- scripts/packageComponent.js
- scripts/packageThemes.js
- scripts/packageTorClient.js
This adds a new CRX3 format by using a Chromium binary to generate the CRX files.
That is I use a Chromium binary instead of the node module `crx`.
It also uses a new fork of `unzip-crx` which I created here: 
https://github.com/brave/unzip-crx/commit/85baf0b54c243c4ed836d161bcf145a4d4611567
https://github.com/brave/unzip-crx/commit/9a5497b0bd9232b56572b487229513bee957db12
Which is published to npm here: 
https://www.npmjs.com/package/unzip-crx-3
I also did a PR to the original repo in case they will accept it. 
After this work we still needed to patch brave-core because publisher key wasn't supported still
https://github.com/brave/brave-core/pull/369
I also noticed that json files were generated in a new location when that was meant to just be vault-updater's path all along. I fixed it …
> Add support for generating CRX3 format

- lib/util.js
Fix https://github.com/brave/brave-core-crx-packager/issues/16
It turns out I didn't need to fork the updateExtensions.js file
> Use brave-core s3

- README.md
- lib/util.js
- package-lock.json
- package.json
- scripts/packageComponent.js
- scripts/packageIpfsDaemon.js
- scripts/packageThemes.js
- scripts/packageTorClient.js
- scripts/uploadComponent.js
- scripts/uploadIpfsDaemon.js
- scripts/uploadThemes.js
- scripts/uploadTorClient.js
Fixes #20
Package an extension and note version number used (output to console):
```
npm run package-ad-block -- --keys-directory keys \
--binary /c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe
```
Upload the extension to test DynamoDB endpoint:
```
npm run upload-ad-block -- --crx-directory build/ad-block-updater/ \
--endpoint http://localhost:8000
```
Package the same extension and note version number increases by one:
```
npm run package-ad-block -- --keys-directory keys \
--binary /c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe
```
> Auto increment extension versions

- README.md
- lib/util.js
- package-lock.json
- package.json
- scripts/importCWSComponents.js
- scripts/packageComponent.js
- scripts/packageIpfsDaemon.js
- scripts/packageThemes.js
- scripts/packageTorClient.js
- scripts/uploadComponent.js
- scripts/uploadIpfsDaemon.js
- scripts/uploadThemes.js
- scripts/uploadTorClient.js
Fixes #30
Eliminates the `--vault-updater-path` option from our scripts, since it's no longer needed. Dropping the option itself was simple, but release-tools had a lot of assumptions about vault-updater baked in. Seemed easiest to just drop release-tools as a dependency and migrate the S3 upload code (essentially just a single function) to our utility script.
> Remove vault-updater-path option, which is no longer needed

- README.md
- manifests/local-data-files-updater/default-manifest.json
- package.json
- scripts/packageComponent.js
- scripts/uploadComponent.js
In preparation for adding additional datasets under 1 `.crx` file, we are migrating the tracking protection component to a more generic "local data files" component. Currently it only contains the tracking protection data, but future versions may contain other datafiles for other Brave services.
The brave-core piece of this is https://github.com/brave/brave-core/pull/1279
> migrate tracking protection to local data files

- scripts/packageComponent.js
fix https://github.com/brave/brave-core-crx-packager/issues/48
`Local-Data` extension was failing the build with this error:
```
13:57:34 
13:57:35 Unhandled rejection: { Error: ENOENT: no such file or directory, open 'manifests/local-data-files-updater/ExtensionWhitelist-manifest.json'
13:57:35     at Object.openSync (fs.js:450:3)
13:57:35     at Object.readFileSync (fs.js:350:35)
13:57:35     at Object.parseManifest (/Users/jenkins/jenkins/workspace/brave-core-ext-local-data-files-update-publish-dev/lib/util.js:77:19)
13:57:35     at processDATFile (/Users/jenkins/jenkins/workspace/brave-core-ext-local-data-files-update-publish-dev/scripts/packageComponent.js:121:31)
13:57:35     at Array.forEach (<anonymous>)
13:57:35     at util.createTableIfNotExists.then …
```
> Issue 48: ExtensionWhitelist should use the default manifest

- package-lock.json
- package.json
- scripts/generateAdBlockRustDataFiles.js
- scripts/packageComponent.js
This PR adds code to package the ad-block Rust data file. 
Unlike the existing `brave/ad-block` packaging, there is no version associated with the serialized files. 
Instead we'll try to always make it backwards compatible.
Since our `brave/go-update` server doesn't have the ability to gate on version yet, we're just going to package both the old and the new ad-block data files into each CRX file for now.  The old clients will just ignore the new file. The new client will ignore the old file in the version directory.  We'll eventually deprecate the old data files.
cc @mihaiplesa we'll need to modify the ad-block rule once this lands to run:
`npm run data-files-ad-block-rust` just before running `npm run data-files-ad-block` and to make sure Rust is installed.
> Add script for generating adblock-rust files

- package-lock.json
Fixes #70 
This PR is a result of running `npm install` twice in the repo.
To test this branch, I:
1. deleted the `node_modules` directory
2. ran `npm install`
3. verified `package-lock.json` is unchanged
4. ran `npm run data-files-https-everywhere`
> Update package-lock.json for new https-everywhere-builder deps

- .gitmodules
- package-lock.json
- package.json
- scripts/generateAdBlockRustDataFiles.js
Similar to #73, but using the newer `web_accessible_resources` and `scriptlets.js` resources from the uBlock Origin repo.
Brave's audited [fork of uBlock Origin](https://github.com/brave/uBlock) is added as a submodule.
> JSON adblock resources support

- package.json
- scripts/generateNTPSponsoredImages.js
- scripts/packageNTPSponsoredImagesComponents.js
- scripts/uploadComponent.js
This PR create only sample en-US localed component crx for test purpose.
Later, this will create components all supported all locales.
To generate data set:
- npm run generate-ntp-sponsored-images -- --data-url="data-url that refers zipped data file"
- data set is stored at ./build/ntp-sponsored-images/resources
To package crx files:
- npm run package-ntp-sponsored-images -- --binary "chromium bin path"  --keys-directory "dirs that stores private files"
- crx files are stored at ./build/ntp-sponsored-images/output/ntp-sponsored-images-en-US.crx (in en-US case)
To upload crx files:
- npm run upload-ntp-sponsored-images-components -- --crx-directory "above outout crx files directory"
> Support NTP sponsored images component

- scripts/generateNTPSponsoredImages.js
Data file will be provided per locale instead of using unified
data.zip. Passed data url should be the parent url.
If passed url is "www.brave.com/resources/",
"www.brave.com/resources/en-US.zip" is the data url for en-US.
> Use separate data url per locale

- scripts/packageTorClient.js
Fix #82
1. Download binaries from: 
```
https://s3.us-east-2.amazonaws.com/demo-tor-binaries/tor-0.3.5.8-darwin-brave-0
https://s3.us-east-2.amazonaws.com/demo-tor-binaries/tor-0.3.5.8-linux-brave-0
https://s3.us-east-2.amazonaws.com/demo-tor-binaries/tor-0.3.5.8-win32-brave-0.exe
```
2. Verify the sha512 sum is correct
> Fix #82: Updating checksum for newly published tor binaries

- lib/util.js
- scripts/uploadComponent.js
DB should be updated after crx uploading is done.
If DB is updated first, update server could be in inconsistent
state before upload is finished.
According to the log (https://ci.brave.com/view/all-extensions/job/brave-core-ext-ntp-sponsored-update-publish-dev/40/console), crx is uploaded first and then db is updated.
fix https://github.com/brave/brave-browser/issues/8037
> Modify crx uploading logic

- README.md
- package.json
- scripts/generateNTPSuperReferrer.js
- scripts/packageNTPSuperReferrerComponent.js
- scripts/uploadComponent.js
Issue: https://github.com/brave/brave-browser/issues/8218
> Generate NTP Super Referrer(SR) component

- package.json
- scripts/generateClientModelParameterFiles.js
- scripts/packageClientModelParameterComponent.js
- scripts/uploadComponent.js
unblock https://github.com/brave/brave-browser/issues/8396
> Add client model parameter updates

- package.json
- scripts/generateNTPSuperReferrerMappingTable.js
- scripts/packageNTPSuperReferrerMappingTableComponent.js
- scripts/uploadComponent.js
Issue - https://github.com/brave/brave-browser/issues/8218
Generating/Upload mapping component that has https://mobile-data.s3.brave.com/superreferrer/map-table.json.
> Generate super referral mapping table component

- scripts/generateNTPSuperReferrer.js
Issue: https://github.com/brave/brave-browser/issues/8218
Backend will not use different metadata file name for SI and SR.
Backend will determine whether it's SI or SR by the contents of metadata.
So, we don't need to use different filename.
In backend, `photo.json` will be used because it's already used by SI.
Please see backend changes - 
https://github.com/brave/brave-core/pull/4866/commits/a3eeb48e76d50019bd8175168f6e8498ec80fdec#diff-992d3e514ddb745d42ac450231255edfR39
> Make SR use same metadata file name with SI

- scripts/generateNTPSponsoredImages.js
- scripts/packageNTPSponsoredImagesComponents.js
Added target regions and excluded target regions list option.
With these two options, we don't need to update whole region's component when we want to update only some regions.
Related devops issue: https://github.com/brave/devops/issues/3038
If `AU,GB,US` is set as target-region, only these three region's components are updated.
If `IN` is set as a excluded-target-region, all regions except `IN` region are updated.
Fix https://github.com/brave/brave-browser/issues/8173
> Support region subset packaging for SI component

- package-lock.json
- package.json
Currently unable to run due to the old Lithuanian list URL (margevicius.lt) having an invalid certificate. 0.2.9 contains [this commit](https://github.com/brave/adblock-rust/commit/73786e56b545c44920923cfdd4656edbd3e4744c) which should resolve the issue.
> Update adblock-rs to 0.2.9 to fix Lithuanian list URL

- lib/util.js
Fix #123 
To get the number of downloads per component and version, we need to add tags to all the components uploaded to the S3 bucket. 
Tag is of the form `component-name=component-name` and `version=component-name/latest`.
> Fix 123: Add tags to extensions uploaded to the S3 bucket

- lib/util.js
Fix #129
1. Handle the first version correctly while adding tags
2. Remove characters restricted in S3 tags. See here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions
>  Fix #129: Fix tagging for super referrers

- lib/util.js
Fix #132 
`+-=` was interpreted as range `+ to =` which included multiple special characters.
> Fix #132: regex for removing restricted characters for S3 tags

- lib/adBlockRustUtils.js
I've created the new https://github.com/brave/adblock-resources repository where Brave can host its own adblock resources for use with adblock-rust. There are no resources hosted there as of yet, but @pes10k is planning to push one soon.
There is a verification script as part of that repository which ensures the resources are in the correct format to be accepted by adblock-rust. This PR enables the CRX packager to pull resources from that repository in addition to the existing resources from the uBO fork.
> Pull adblock resources from brave/adblock-resources

- scripts/generateNTPSponsoredImages.js
- scripts/generateNTPSuperReferrer.js
- scripts/generateNTPSuperReferrerMappingTable.js
Returns non-zero when get errors.
Then, jenkins job will not execute next commands.
So far, json syntax error of photo.json/data.json is ignored. (ex, https://ci.brave.com/view/all-extensions/job/brave-core-ext-ntp-sponsored-publish/64/console -> Success reported)
Resolves https://github.com/brave/brave-browser/issues/10689
> Handle errors gracefully for NTP SI/SR jobs

- package-lock.json
- package.json
- scripts/generateAdBlockRustDataFiles.js
This adds support for hosts-based filter list formats, as reported by the default and regional filter list descriptors.
> Update adblock-rust to v0.3 API

- scripts/generateAdBlockRustDataFiles.js
As of https://github.com/brave/adblock-resources/pull/4 we are moving to host filter lists in the [adblock-resources](https://github.com/brave/adblock-resources) repository, instead of in adblock-rust.
This change updates the DAT builder to pull lists from `filter_lists/default.json` and `filter_lists/regional.json` in the master branch of that repository.
adblock-resources has a verification script to ensure that these files always contain valid content in any PRs merged against master.
In addition, this change produces a new file called `regional_catalog.json` in the `build/ad-block-updater/default` folder, which is essentially `filter_lists/regional.json` from the adblock-resources repo. When shipped alongside the default DAT, `brave-core` will be able to always show the most recently …
> Read lists from adblock-resources

- scripts/packageComponent.js
Previous attempt didn't package the stylesheet correctly, this commit fixes that but renames the manifest and component itself
> fix SpeedReader packaging to include stylesheet

- README.md
The current URL in the README is broken - regional lists are now stored in the `adblock-resources` repository rather than `adblock-rust`.
> Update readme to point to new regional list URL

- lib/util.js
> Fix #169: Skip tagging if the previous component does not exist

- package.json
- scripts/packageComponent.js
Include the `scripts` directory when packaging Greaselion. Previously, only `Greaselion.json` was being included in the CRX.
> Include scripts directory when packaging Greaselion

- package-lock.json
- package.json
Contains fixes from https://github.com/brave/adblock-rust/pull/135.
> Update adblock-rust to support correct important/redirect behavior

- lib/adBlockRustUtils.js
- scripts/generateAdBlockRustDataFiles.js
- scripts/generateManifestForRustAdblock.js
Follow up from #125; I hadn't realized we used the `lists` method separately in another location to generate adblock manifest files. I've abstracted the newer behavior out into `lib/adBlockRustUtils.js` so that the same logic can be used both there and in the DAT file creation step.
> Remove last use of adblock-rust's list API

- scripts/packageComponent.js
Now that we include localizations with Greaselion scripts, we need to update `getNormalizedDATFileName` to use the default manifest for `messages.json` files. Without this fix, we're receiving the following error when attempting to deploy a new Greaselion script:
```
14:58:08  Unhandled rejection: Error: ENOENT: no such file or directory, open 'manifests/local-data-files-updater/messages-manifest.json'
14:58:08      at Object.openSync (fs.js:447:3)
14:58:08      at Object.readFileSync (fs.js:349:35)
14:58:08      at Object.parseManifest (/Users/jenkins/jenkins/workspace/brave-core-ext-local-data-files-update-publish/lib/util.js:79:19)
14:58:08      at processDATFile (/Users/jenkins/jenkins/workspace/brave-core-ext-local-data-files-update-publish/scripts/packageComponent.js:199:31) …
```
> Include messages localizations file in DAT file normalization list

- package-lock.json
- package.json
There were some additional changes added by an upstream dependency in the package lock file, I tried to keep the commits clean to make that obvious.
> Bump ethereum-remote-client to 0.1.79

- scripts/downloadIpfsDaemon.js
- scripts/packageIpfsDaemon.js
Resolve https://github.com/brave/brave-browser/issues/13487
Note: Please don't merge it yet as I'm still building brave-core-ext-ipfs-component-publish-dev to test the update on dev first.
> Update go-ipfs to v0.7.0

- package-lock.json
Pulls in updates from `autoplay-whitelist` and `extension-whitelist` to support building on more recent Node versions, including the current v15.6.x.
> Support building on node v12+

- package-lock.json
- package.json
For whatever reason, the npm version of adblock-rust has been compiled without support for regex rules. They are enabled in-browser, but the rulesets served from here are built using the npm version, and so we are running into issues like https://github.com/brave/brave-browser/issues/14140. I've updated the dependency here to include https://github.com/brave/adblock-rust/commit/07f22810f1332895abb71286763a10bb2b555bdd, which should solve this problem.
> Update adblock-rust to support full-regex-handling

- lib/ntpUtil.js
Fixed assigning to const var schemaVersion.
Found this issue while testing https://github.com/brave-experiments/ntp-si-assets/pull/256
> Fixed failure when photo.json is empty object

- lib/adBlockRustUtils.js
- package-lock.json
- package.json
- scripts/generateAdBlockRustDataFiles.js
This version adds support for `$document` filter rules in the generated DAT files.
> Update adblock-rust to 0.3.7

- package-lock.json
- package.json
This updates the uBlock Origin submodule to the latest change merged in https://github.com/brave/uBlock, as well as the necessary changes in `adblock-rust` to support the newer resources..
This also updates the `package-lock.json` file to version 2, which *should* be compatible with our infrastructure.
> Update uBlock Origin submodule

- package-lock.json
- package.json
`adblock-rust` v0.3.13 addresses the issue that caused the `json-prune` scriptlet to be a no-op.
> Update uBlock Origin submodule (attempt 2)

- scripts/downloadIpfsDaemon.js
- scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/16913
Added fs-repo tool into crx to make proper migrations for ipfs repo
> Added fs-repo tool for darwin extension

- package-lock.json
- package.json
- scripts/generateAdBlockRustDataFiles.js
This includes a small tweak to where `$redirect` rules are stored in the serialization format. The goal is to support a future change to the in-browser matching algorithm such that the newer `$redirect-rule` option can also work. Existing clients should not experience any differences in matching behavior as a result of this change.
More details available at https://github.com/brave/adblock-rust/issues/169#issuecomment-916471765.
> Update adblock-rust to v0.3.17

- package.json
- scripts/packageComponent.js
Now that debouncing has landed in master, this will add the new `debounce.json` configuration file to the local data files component.
Dependent on https://github.com/brave/adblock-lists/pull/645 for a package file, but otherwise straightforward.
> add debounce configuration to local data files component

- scripts/packageComponent.js
Fix https://github.com/brave/brave-browser/issues/18216
Copy images too for the wallet data files
> Package token images in wallet data files

- scripts/downloadIpfsDaemon.js
- scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/17934
Revert fs-repo-10-to-11 migration node update because 0.10 handles it natively
Add update to 0.10.0-rc2
> Update ipfs node to 0.10.0

- .github/CODEOWNERS
- .github/workflows/assign-pr.yml
- .github/workflows/submodule-update.yml
Resolves https://github.com/brave/devops/issues/6097 for Formatting Review
This set of GitHub actions will:
Run periodically at a set schedule (once per day), and check for updates in the uBlock submodule.
If there are updates available, it will trigger the generation of a PR assigned to a specific user defined in codeowners.
> Add automated PR creation on submodule updates

- package-lock.json
- package.json
This includes a fix for the CSS exfiltration attack described in https://portswigger.net/research/ublock-i-exfiltrate-exploiting-ad-blockers-with-css
> Update adblock-rust to v0.4.2

- lib/util.js
- manifests/wallet-data-files-updater/manifest.json
- package-lock.json
- package.json
- scripts/packageComponent.js
- Makes the wallet data files script easy to maintain
- Adds in https://github.com/brave/token-lists/blob/main/evm-contract-map.json for Ropsten tokens
- Makes it easier to add Solana tokens in another PR.
Please also review the initial work to generate the lists here https://github.com/brave/token-lists/commits/main
The way it works is that repo makes the exact thing we deliver in brave-core-crx-packager and publishes just those json files and images to npm.  Then in this repo we just include that simple dep which has no sub-deps.
Fix: https://github.com/brave/brave-core-crx-packager/issues/307
> Rewrite script for packaaging wallet data files

- package-lock.json
- package.json
`adblock-rust` 0.4.3 adds support for `$doc` as an alias for `$document`. This option alias appears in some lists that Brave uses, but they've been silently ignored so far, as reported in https://github.com/brave/adblock-rust/issues/197.
> Update to adblock-rust 0.5.0

- package-lock.json
- package.json
Reverts brave/brave-core-crx-packager#344
Per @linhkikuchi:
```
this PR make new build failing https://github.com/brave/brave-core-crx-packager/pull/344/files,
we have this issue before, need to revert this. cc @simonhong can you update dependencies
and fix error so that we will not run into this again?
```
> Revert "Update dependency brave-wallet-lists to v1.0.2"

- package-lock.json
- package.json
Follow-up on https://github.com/brave/brave-core-crx-packager/pull/344. Manually bumped the version and performed `npm install` with npm version 6.14.0 to avoid upgrade to new lockfile format.
> Bump brave-wallet-lists to 1.0.2

- lib/util.js
- scripts/ntp-sponsored-images/package.js
- scripts/packageBraveAdsResourcesComponent.js
- scripts/packageComponent.js
- scripts/packageIpfsDaemon.js
- scripts/packageNTPBackgroundImagesComponent.js
- scripts/packageNTPSuperReferrerComponent.js
- scripts/packageNTPSuperReferrerMappingTableComponent.js
- scripts/packageTorClient.js
- scripts/packageYoutubedown.js
Relates https://github.com/brave/brave-browser/issues/873
Devops PR: https://github.com/brave/devops/pull/6965
The purpose of this PR is to add extra signing (a publisher proof) to all brave CRX.
The plan:
[DONE] (brave-core) [add code to generate  and verify a publisher proof](https://github.com/brave/brave-core/pull/12090)
[DONE] (devops) add new credentials
[in progress](devops) change browser from Chrome to Brave (maybe Brave Nightly?)
[in progress] (devops) pass the credentials to  [brave-core-crx-packager](https://github.com/brave/brave-core-crx-packager) signing scripts
[here] (brave-core-crx-packager) pass the new key to Brave (when we making crx by passing a special command-line)
The devops changes is in progress
> Support publisher proof

- scripts/generateAdBlockRustDataFiles.js
Fixes https://github.com/brave/brave-core-crx-packager/issues/370
This will be ignored by packageComponent.js
See `getDATFileListByComponentType` where `test-data` folder is excluded
> Update iOS cosmetic filter output to be in test-data folder

- package-lock.json
- package.json
brave-wallet-lists was updated to 1.1.6 here https://github.com/brave/token-lists/pull/14
Also had such ci failures, hence package_lock updates
```
Run npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: ansi-styles@3.2.1 from lock file
npm ERR! Missing: color-convert@1.9.3 from lock file
npm ERR! Missing: color-name@1.1.3 from lock file
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
npm ERR! [--script-shell <script-shell>]
npm ERR! 
npm ERR! aliases: …
```
> bump brave-wallet-lists to 1.1.6

- README.md
- package-lock.json
- package.json
- scripts/generateYoutubedown.js
- scripts/packageYoutubedown.js
As youtubedown.js is no longer supported, we're using our own script.
So, packages playlist-component as youtubedown.js. In this way,
we can reuse existing jenkins jobs.
[playlist-component](https://github.com/brave/playlist-component)
Resolves https://github.com/brave/brave-browser/issues/24094
> Replace youtubedown.js with playlist-component

- package.json
- scripts/packageAdBlock.js
- scripts/packageComponent.js
Many of the other packaging scripts have their own logic in separate files. There is planned work on the adblock component packaging; separating this out into its own step will make it much easier to upgrade in the future.
> Move ad-block-updater packaging into its own script

- lib/adBlockRustUtils.js
- scripts/generateAdBlockRustDataFiles.js
- scripts/generateManifestForRustAdblock.js
- scripts/packageAdBlock.js
Corresponds to https://github.com/brave/adblock-resources/pull/81 - these two changes can be merged in any order.
In addition to support for shipping plaintext adblock list formats in components, this adds a new component for the regional catalog and adblock resources. These change much less frequently than the rest of the adblock data, so the versions can be can be bumped independently to reduce bandwidth. This should also simplify logic in `brave-core` significantly.
The new components are addressed by component ID, rather than UUID, to reduce complexity in the future (https://github.com/brave/adblock-resources/issues/80).
New components:
- Regional Catalog `gkboaolpopklhgplhaaiboijnklogmbc`
- Resources `mfddibmblmbccpadfndgakiopmmhebop`
- Cookie List plaintext format …
> Support plaintext adblock components

- scripts/packageAdBlock.js
Default component needs `ad-block-updater-default.pem`, not `ad-block-updater.pem`. Didn't catch this when testing locally since it was in a `if (!localRun) {...}` block.
> Fixup for default adblock CRX packaging

- .gitignore
- package-lock.json
- package.json
- scripts/packageComponent.js
As per https://github.com/brave/brave-core-crx-packager/issues/467:
- the list downloads to override the `clean-urls` and `debounce` list versions from the outdated `adblock-lists` dependency were copied [from CI](https://github.com/brave/devops/blob/master/jenkins/jobs/extensions/dev/brave-core-ext-local-data-files-update-publish-dev.yml#L43-L45) into the `data-files-local-data-files` npm script
- the `adblock-lists` npm dependency was removed, since it's not used anywhere else and even those two files from it were being overridden
Once this is merged, we should be able to remove those special-cased download steps from CI.
> Include JSON list updates in data-files-local-data-files build script

- lib/adBlockRustUtils.js
- scripts/generateAdBlockRustDataFiles.js
- scripts/generateManifestForRustAdblock.js
I generated a new component ID and pubkey for the plaintext format of our default adblock lists; the corresponding PEM has been uploaded to 1Password and is updated in Jenkins as well. This PR uses them to generate a new plaintext component version of the default lists.
> Ship default adblock lists in plaintext format

- scripts/generateAdBlockRustDataFiles.js
Shows the specific URL that failed to download, which helps to diagnose the issue
> Better error messages when adblock list downloads fail

- lib/util.js
- scripts/packageAdBlock.js
- scripts/uploadComponent.js
The new independent components for adblock resources and the adblock regional catalog change very infrequently, but their versions are still incremented and new versions are sent to users daily. Some regional adblock lists are also updated less frequently than every day.
If we can avoid re-packaging and shipping unchanged components to users who already have the most recent version, we can probably save a significant amount of CDN bandwidth.
Generate a hash of the content for a particular component. Save it to a file with the same name as the CRX, but with a `.contentHash` extension instead of `.crx`. This file can contain an arbitrary string; for these adblock components I've used a SHA256 hash of either `list.txt`, `resources.json`, or `regional_catalog.json`, depending on which type of …
> Cache adblock component content hashes, avoid version bumps if they haven't changed

- CHANGELOG-go-ipfs.md
(Also fixed a typo in the previous commit.)
> Add kubo 0.16.0 release notes

- .github/workflows/submodule-update.yml
As of https://github.com/mheap/submodule-sync-action/pull/5, we can now supply a description for the automated PRs.
I added a brief sentence that provides some context about why the change is requested, as well as a link to the corresponding changes that should be reviewed.
> Add pr_body to submodule update action

- .github/workflows/node.js.yml
- package-lock.json
- package.json
- scripts/packageComponent.js
- scripts/uploadComponent.js
Closes https://github.com/brave/brave-core-crx-packager/issues/471
https://github.com/brave/brave-core/pull/14929 is in Release now (1.45.x), so no new Brave installs will attempt to fetch the speedreader component.
Note: I believe the CRX and component info will still exist indefinitely in S3 until it's manually removed.
> Remove speedreader component

- lib/adBlockRustUtils.js
- lib/ntpUtil.js
- lib/util.js
- package-lock.json
- package.json
- scripts/generateAdBlockRustDataFiles.js
- scripts/generateBraveAdsResourcesComponentInputFiles.js
- scripts/generateNTPBackgroundImages.js
- scripts/generateNTPSuperReferrerMappingTable.js
The `request` package is deprecated and unmaintained. The same functionality can be achieved with the built-in `fetch` API, so I removed the dependency and updated the code accordingly.
Progress towards https://github.com/brave/brave-core-crx-packager/issues/380.
> Replace `request` with `fetch`

- lib/ntpUtil.js
- scripts/generateBraveAdsResourcesComponentInputFiles.js
- scripts/generateNTPBackgroundImages.js
- scripts/generateNTPSuperReferrerMappingTable.js
Followup to #528 (oopsie :sweat_smile:)
Closes https://github.com/brave/brave-core-crx-packager/issues/538
> Fix fetch calls to use .then instead of callback argument

- package-lock.json
Updates brave-site-specific-scripts to latest version, which includes:
* https://github.com/brave/brave-site-specific-scripts/pull/90
* https://github.com/brave/brave-site-specific-scripts/pull/89
Changes have been tested by QA in the dev environment.
> Update brave-site-specific-scripts version.

- lib/util.js
Need more context to debug a failure on the server
> log when the key for packaging an adblock component is missing

- package-lock.json
- package.json
We install `brave-wallet-lists` directly in devops in order to keep the package up-to-date on every CI run.
See relevant devops PRs for further information: https://github.com/brave/devops/pull/9073 and https://github.com/brave/devops/pull/9072
> Remove brave-wallet-lists from package.json

- scripts/downloadIpfsDaemon.js
- scripts/packageIpfsDaemon.js
Resolves https://github.com/brave/brave-browser/issues/27965
Tested: https://github.com/brave/brave-core-crx-packager/pull/574
> Update kubo to 0.18.1

- package.json
- scripts/uploadComponent.js
The `--type` argument to `uploadComponent` is currently unused.
We have all 14 of these in `package.json`, which only differ by the unused `--type` argument:
```json
"upload-ethereum-remote-client": "node ./scripts/uploadComponent --type ethereum-remote-client",
"upload-ad-block": "node ./scripts/uploadComponent --type ad-block-updater",
"upload-https-everywhere": "node ./scripts/uploadComponent --type https-everywhere-updater",
"upload-ipfs-daemon": "node ./scripts/uploadComponent --type ipfs-client-updater",
"upload-wallet-data-files": "node ./scripts/uploadComponent --type wallet-data-files-updater",
"upload-tor-client": "node ./scripts/uploadComponent --type tor-client-updater",
"upload-tor-pluggable-transports": "node ./scripts/uploadComponent --type tor-pluggable-transports", …
```
> Add generic upload-component npm script, intended to replace specialized variants

- lib/adBlockRustUtils.js
- lib/ntpUtil.js
- lib/util.js
- package.json
- scripts/downloadIpfsDaemon.js
- scripts/generateAdBlockRustDataFiles.js
- scripts/generateBraveAdsResourcesComponentInputFiles.js
- scripts/generateManifestForRustAdblock.js
- scripts/generateNTPBackgroundImages.js
- scripts/generateNTPSuperReferrer.js
- scripts/generateNTPSuperReferrerMappingTable.js
- scripts/generateYoutubedown.js
- scripts/importCWSComponents.js
- scripts/ntp-sponsored-images/generate.js
- scripts/ntp-sponsored-images/package.js
- scripts/ntp-sponsored-images/params.js
- scripts/ntp-sponsored-images/params.test.js
- scripts/ntp-sponsored-images/region-platform-component-metadata.js
- scripts/packageAdBlock.js
- scripts/packageBraveAdsResourcesComponent.js
- scripts/packageComponent.js
- scripts/packageIpfsDaemon.js
- scripts/packageNTPBackgroundImagesComponent.js
- scripts/packageNTPSuperReferrerComponent.js
- scripts/packageNTPSuperReferrerMappingTableComponent.js
- scripts/packageTorClient.js
- scripts/packageTorPluggableTransports.js
- scripts/packageYoutubedown.js
- scripts/uploadComponent.js
- test/generateResourcesFile.js
Will be required for importing the [new scriptlets format](https://github.com/gorhill/uBlock/commit/18a84d2819d49444fc31c5350677ecc5b2ec73c6) from uBlock Origin, i.e.:
`lib/adBlockRustUtils.js`
```js
const { builtinScriptlets } = await import('../submodules/uBlock/assets/resources/scriptlets.js');
```
I've done `npm run test` and ran through the adblock-specific scripts, but haven't tested the others - help would be appreciated there.
> Convert everything to ES Modules

- package-lock.json
- package.json
- scripts/ntp-sponsored-images/params.test.js
- test/generateResourcesFile.js
~Pending #596.~
`tap` pulls in a ton of extra dependencies; we can reduce the `package-lock.json` file by almost 14k lines by removing it. The builtin `node:test` module is similar enough to almost be a drop-in replacement.
This solves the audit failure for `request`.
> replace tap with builtin node:test module

- lib/adBlockRustUtils.js
- lib/util.js
- scripts/generateAdBlockRustDataFiles.js
This should help limit the number of times the `brave-core-ext-ad-block-update-publish` job needs to be re-run.
> Retry failed requests

- lib/util.js
- package-lock.json
- package.json
AWS SDK v2 is going into maintenance mode, and has a few deprecated transitive dependencies. AWS SDK v3 is modularized which should in theory reduce size*, since we only need to pull in parts of the SDK that are used.
According to the steps on https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html, I used
```
npx aws-sdk-js-codemod -t v2-to-v3 lib/util.js
```
to automatically perform the migration.
We'll have to run this in staging CI to test it.
<sub> * note the PR has 5412 additions and 2808 deletions (primarily coming from `package-lock.json`), and my `node_modules` has _grown_ by 21M after a clean & install on this branch :thinking:</sub>
> Update to aws-sdk v3

- CHANGELOG-go-ipfs.md
Closes : https://github.com/brave/qa-resources/issues/525
> Release notes for Kubo 0.20.0

- lib/adBlockRustUtils.js
Replaces #595.
Requires:
- `brave-core` https://github.com/brave/brave-core/pull/17858 (uplifted to Release 1.50.x). 
- `brave-ios` https://github.com/brave/brave-ios/pull/7195 (merged to 1.50.x).
To summarize the changes:
- some of the scriptlets now rely on a `scriptletGlobals` object which must be shared between all the scriptlets in each page with injections (https://github.com/brave/brave-browser/issues/29435, related to https://github.com/gorhill/uBlock/commit/5c9c87e485308cb2dc6da102a0e20d8fce84124e)
- some scriptlets have dependencies. To handle this for now, I'm bundling all dependencies with the scriptlets that need them, even if it might result in some duplicated code in each page for multiple injections (related to https://github.com/gorhill/uBlock/commit/236fb3ad59ecf3e0106600 …
> Update code to support new uBlock Origin scriptlets format

- package-lock.json
This fixes 2 out of the 7 outstanding `npm audit` moderate severity issues.
> Update optionator using `npm audit fix`

- scripts/packageBraveAdsResourcesComponent.js
removes packaging of en-lang components since they are not being updated. this saves incrementing the version and forcing users to download the same (large) file on every ads resources jenkins run.
I tested against this job https://ci.brave.com/job/brave-core-ext-user-model-installer-publish-dev/295/
and pointed to staging components.
The client will download the last file, so no risk of users not having files.
```
*Nightly/Staging*
brianfung Library/Application Support/BraveSoftware $ jq . Brave-Browser-Nightly/ocilmpijebaopmdifcomolmpigakocmo/1.0.122/bvkgcaxyaitmhkbbqnqnqugrjeqzspxv | wc -l
372373
brianfung Library/Application Support/BraveSoftware $ jq . Brave-Browser-Nightly/ocilmpijebaopmdifcomolmpigakocmo/1.0.122/emgmepnebbddgnkhfmhdhmjifkglkamo | wc -l
1490627
*Release/Production* …
```
> remove en from packager script

- package-lock.json
`semver 6.3.1` fixes an ongoing audit failure. Renovate hasn't picked it up in a while, for some reason.
> Fix audit failure (`semver`)

- scripts/packageTorClient.js
Our current certificate expires next month. The devops code has already been updated to sign binaries with a new certificate. This PR allows us to release a new version of the main Tor binary, which will then be signed with the new cert and rolled out to users because it has a higher version number.
> Codesign Windows Tor client with new certificate

- lib/adBlockRustUtils.js
uBO doesn't error out on missing dependency functions, but we do here. I can revisit that later if necessary, but in the meantime I'd prefer to keep the stricter validation.
> Temporary workaround for missing scriptlet dependency function

- package-lock.json
Update brave-site-specific-scripts version for Greaselion release.
Related to https://github.com/brave/brave-browser/issues/32107
> Update brave-site-specific-scripts version

- lib/adBlockRustUtils.js
Fixed upstream in https://github.com/gorhill/uBlock/commit/8bf1ed954d87d2e73b67b4c84d7cdfdd64fdd51b
> Remove temporary workaround for `get-extra-args-entries.fn`

- lib/adBlockRustUtils.js
- lib/util.js
- scripts/generateAdBlockRustDataFiles.js
- scripts/generateManifestForRustAdblock.js
Required for https://github.com/brave/brave-core/pull/19946
Depends on https://github.com/brave/adblock-resources/pull/130
Will update `listCatalogUrl` prior to merging - right now it points to the `unified-catalog` branch of `adblock-resources`.
`list_catalog.json` is added directly into the existing regional catalog component. `regional_catalog.json` is still generated from the contents of `list_catalog.json` and added there for backwards compatibility. It can be removed once most users have updated beyond the versions where `list_catalog.json` is supported.
> Support unified adblock catalog

- scripts/generateAdBlockRustDataFiles.js
- `adblock-rust-ffi` has moved and uses a completely different test setup now
- `brave-core` has removed DAT handling code and the corresponding test data files
- iOS is our only codebase still using the DAT format, but is nearly migrated and doesn't use these files to my knowledge
> Remove adblock test data files

- lib/adBlockRustUtils.js
The `permission` field corresponds to the format from https://github.com/brave/adblock-rust/pull/300/commits/a7a385a76ba9d0457aa68df4ddcb152fd222d533
> Populate resource permission field

- scripts/generateManifestForRustAdblock.js
To solve the most recent errors on adblock publish due to https://adblock.ee
> Skip generating manifests for nonexistent directories

- lib/util.js
- scripts/ntp-sponsored-images/package.js
- scripts/packageAdBlock.js
- scripts/packageBraveAdsResourcesComponent.js
- scripts/packageComponent.js
- scripts/packageIpfsDaemon.js
- scripts/packageNTPBackgroundImagesComponent.js
- scripts/packageNTPSuperReferrerComponent.js
- scripts/packageNTPSuperReferrerMappingTableComponent.js
- scripts/packageTorClient.js
- scripts/packageTorPluggableTransports.js
- scripts/packageYoutubedown.js
Incremental work towards https://github.com/brave/brave-core-crx-packager/issues/622.
This PR refactors duplicated logic across all packaging scripts to use common `stageFiles` and `stageDir` utilities, removing a net of almost 100 lines.
In the future I'd like to consolidate all components into using just one of these utilities, however I've left that for a followup as it requires deeper understanding of each component being packaged and cleanup of some legacy backwards-compatible code.
> Deduplicate file staging logic

- scripts/ntp-sponsored-images/package.js
- scripts/packageBraveAdsResourcesComponent.js
Fixes an issue introduced in #740 
These two instances of `stageDir` aren't bound so there is no `this` argument to pass.
> remove undefined argument from stageDir

- package.json
- scripts/packageComponent.js
- scripts/packageLocalDataFiles.js
close inspection of the diffs will reveal a nightmarishly twisted wreck of two completely unrelated logical concepts.
highlights:
- `getDATFileListByComponentType` returned a recursively traversed list of file paths + 5 other hardcoded ones for `local-data-files` jobs, but returned _a list of 1 empty string_ for the other jobs
- the `local-data-files` job produces _ONE_ component, yet the main entry point called `processDATFile` once per file above, with no one-off logic before or after
- for `local-data-files`, each invocation of `processDATFile` would reverse-engineer the location of the exact same manifest template file using `getNormalizedDATFileName`
- `getNormalizedDATFileName` chained together 8 conditions about hardcoded filename strings with no explanation of why or where they …
> Split local-data-files-updater out of `packageComponent`

- lib/adBlockRustUtils.js
With support for quoted args upcoming, template arguments are escaped using JSON string format. JSON only supports double-quoted strings, so these need to be switched for proper compatibility.
> Use double-quoted template strings in scriptlet wrapper

- scripts/generateAdBlockRustDataFiles.js
- scripts/generateManifestForRustAdblock.js
- scripts/packageAdBlock.js
`brave-core` [migrated](https://github.com/brave/brave-core/pull/15077) to using the plaintext list components in 1.46., and `brave-ios` likewise [migrated](https://github.com/brave/brave-ios/pull/7277) to using the plaintext lists in 1.57. Very few users are on any of the older versions; it should be safe to remove this old logic now.
> Remove legacy DAT adblock components

- scripts/packageAdBlock.js
Previously, only directories with a `manifest.json` were considered for packaging. Now we look at the list catalog as the source of truth, but we still need to skip components that were not correctly handled in a previous step.
This would have been avoided by https://github.com/brave/brave-core-crx-packager/pull/844 which combines download, manifest generation, and packaging into one abortable function call per-component.
> Restore the check for missing adblock manifests when packaging

- scripts/generateAdBlockRustDataFiles.js
- scripts/packageAdBlock.js
1st commit resolves extra messages in `#extensions-bot` and publish failures following Sentry warnings (i.e. what https://github.com/brave/brave-core-crx-packager/pull/848 was supposed to do)
2nd commit resolves the <code>internal error in Neon module: byte index 18 is out of bounds of `\,mr=function(r\,`</code> error.
> Fix packaging failures

- CHANGELOG-go-ipfs.md
As per https://bravesoftware.slack.com/archives/C212VB0RG/p1712748480660519?thread_ts=1712577620.951589&cid=C212VB0RG, component was pushed to release on 10th so need to update the release date in notes to match the actual release date.
> Update to correct release date

- scripts/packageAdBlock.js
This was previously using the old filename for compatibility; it should be safe to update based on the new file going forwards.
> Use list_catalog.json for the catalog component file hash

- lib/adBlockRustUtils.js
- package-lock.json
- package.json
- scripts/generateAdBlockRustDataFiles.js
- test/testAdBlock.js
This will block publishing for any adblock component if the list cannot be converted to the syntax needed by iOS.
~Known limitation: a few of the lists are too large for lambda payloads and can't really be checked this way; we ignore them for now. In the future we can set up an endpoint that accepts compressed payloads.~ Resolved!
> Add webkit-content-filter-validator step

- package-lock.json
Update brave-site-specific-scripts version for Greaselion release.
Related to https://github.com/brave/brave-browser/issues/40784
Related to https://github.com/brave/brave-browser/issues/40822
> Update Greaselion version

- scripts/generateAdBlockRustDataFiles.js
Should resolve the following error for now:
```
Not publishing a new version of Brave Ad Block Updater due to failure downloading a source: uBlock Origin 2024 Filters could not be converted to iOS content blocking syntax. Reason: Error while parsing [a-z][a-z+.-]*:\/\//^dizipal\\d+\\\.com\$/[:/]: Start of line assertion can only appear as the first term in a filter.
Content Rule List compiling failed: Compiling failed.
Invalid or unsupported regular expression.
```
I'll investigate the root cause later and make sure adblock-rust is prepared to handle these properly.
> filter out unsupported regex hostnames in cosmetic filters

- lib/ntpUtil.js
SmartNTTs are targeted locally by the browser, and only shown to users if the configured conditions match.
Non-smart capable browsers - that pre-date the introduction of this feature - should never show these NTTs. To enforce this:
- the existing campaigns array in photo.json never includes smartNTTs
- a new campaigns2 array is included in photo.json. This includes all NTTs, including smart ones.
SmartNTT capable browsers read the campaigns2 array. Non-smart capable browsers continue to read the campaigns array.
Assets referenced in either of these arrays need to be included within the crx package.
See https://github.com/brave/ntp-si-assets/pull/1192.
> feat(smartNTT): process assets in new campaign array

- lib/contentSign.js
- lib/util.js
- scripts/packageAdBlock.js
Resolves https://github.com/brave/brave-browser/issues/42274
> Added verified_contents.json generator.

- scripts/generateAdBlockRustDataFiles.js
We'd like to use cached list downloads from a mirror repo to create the adblock components. This should improve the reliability of the system in case individual URLs cannot be downloaded.
> Use mirrored lists to assemble adblock components

- .gitignore
- lib/ntpUtil.js
- lib/ntpUtil.test.js
- scripts/ntp-sponsored-images/generate.js
The ntp-si packaging logic had intimate knowledge of the internal format of `photo.json` in order to determine the set of assets to be included in the crx.
This PR shifts that responsibility to `ntp-si-assets`, which as of https://github.com/brave/ntp-si-assets/pull/1240 now publishes an additional file `assets.json` explicitly containing the list of files to be packaged. See [example](https://mobile-data.s3.brave.com/GB/desktop/assets.json).
This is a pre-req for rich NTTs, which will have a wider variety of assets. That isn't implemented server-side yet: this change is in preparation for reducing the number of places that are impacted when it is. So currently there should be no visible difference with this change: it's a pure refactor.
Re #1039
> refactor(ntp-si): read asset list explicitly

- lib/util.js
- scripts/packageAdBlock.js
Resolves https://github.com/brave/brave-core-crx-packager/issues/1018
> Added --force-next-version command line param.

- component-data/youtube-script-injector/manifest.json
- component-data/youtube-script-injector/scripts/extra-controls-fullscreen.js
- component-data/youtube-script-injector/scripts/extra-controls-pip.js
- component-data/youtube-script-injector/scripts/playback-video.js
- component-data/youtube-script-injector/youtube.json
- package.json
- scripts/packageYouTubeScriptInjector.js
Adds packaging logic for a new component with id `ninjlighifanhiflenpeafpnanjemako`.
Required for https://github.com/brave/brave-core/pull/26355
This will need a new Jenkins job as well.
PEM is uploaded to 1Password `Developers Shared` in `YouTube Script Injector Component`.
> Add YouTube script injector component

- lib/ntpUtil.js
- lib/util.js
- scripts/generateNTPBackgroundImages.js
- scripts/ntp-sponsored-images/generate.js
Teach both the `generate-ntp-background-images` and `generate-ntp-sponsored-images` jobs to permit a `--data-url` in s3 form, as well as https, e.g.:
```
npm run generate-ntp-sponsored-images -- \
--data-url=s3://brave-theme-customizations-dev/ \
--target-regions GB-desktop
```
Which causes them to download directly from the s3 bucket using s3 apis if specified.
On merge of this PR there will be no changes to the execution of the jobs, as the configured `--data-url` will remain https:.
However, I will then subsequently update the jenkins job configs (e.g. [here](https://github.com/brave/devops/blob/c42993bd30f14b186ecff434310220f7fb567640/jenkins/jobs/extensions/brave-core-ext-ntp-sponsored-publish.yml#L45)) to specify an s3: url instead of an https mobile-data url, avoiding the need to …
> feat: support downloading ntp assets directly from s3

- lib/util.js
As said in the aws documentation and explained in [this](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/the-response-object.html) example, we need to use `.name` instead of `.code` member to check the error type.
> The AWS error does not contain a 'code' member. Using 'name' instead.

- lib/contentSign.js
- lib/crx.js
- scripts/packageManifestV2Extensions.js
Verified contents payload requires the use of '/' in paths.
This change enables the generation of verified contents on Windows.
Current CI jobs generates the right content  because they're running on Linux.
Also added export of the verified content to the file for debug purposes.
> Using POSIX paths on all platforms.

- lib/adBlockRustUtils.js
Fixes https://github.com/brave/brave-core-crx-packager/issues/1091 
Running `npm run data-files-ad-block-rust` works on Linux, but not on Windows with this relative path ` ..\submodules\uBlock\src\js\resources\scriptlets.js` generated by the script.
https://github.com/brave/brave-core-crx-packager/blob/f8ad7c2fb06c8856e532cda5f44748a84313515c/lib/adBlockRustUtils.js#L78
This is something that happens often for the way Windows vs Unix handle paths differently and the slashes and all that.
> Fix `[ERR_INVALID_MODULE_SPECIFIER]: Invalid module` in Windows

- package-lock.json
- package.json
- scripts/packageLocalDataFiles.js
For https://github.com/brave/devops/issues/13097
As of brave-core 1.74.x (released January 2025), `brave-site-specific-scripts` is no longer used by the browser.
> Remove brave-site-specific-scripts
